"""Added foreign key to  Roles claims table in  database

Revision ID: 0021a59a8bc4
Revises: 3d0748e57abd
Create Date: 2025-03-15 17:56:12.762607

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0021a59a8bc4'
down_revision = '3d0748e57abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roleclaims', sa.Column('role_claim_id', sa.Uuid(), nullable=False))
    op.add_column('roleclaims', sa.Column('role_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'roleclaims', 'user', ['role_id'], ['id'])
    op.drop_column('roleclaims', 'role_clain_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roleclaims', sa.Column('role_clain_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roleclaims', type_='foreignkey')
    op.drop_column('roleclaims', 'role_id')
    op.drop_column('roleclaims', 'role_claim_id')
    # ### end Alembic commands ###
