"""course  and user relationship updated

Revision ID: 1be6d19a5233
Revises: 8f769a87bbdc
Create Date: 2025-07-04 11:25:32.281424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1be6d19a5233'
down_revision = '8f769a87bbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
