"""supplier  and user relationship updatedby

Revision ID: 30bffdc94577
Revises: 59c602e8e056
Create Date: 2025-07-04 11:29:55.670865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30bffdc94577'
down_revision = '59c602e8e056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
