"""Added Roles claims model to database

Revision ID: 3d0748e57abd
Revises: 8460080fb0bd
Create Date: 2025-03-15 17:42:35.004286

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d0748e57abd'
down_revision = '8460080fb0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roleclaims',
    sa.Column('role_claim_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role_claim_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role_claim_isactive', sa.Boolean(), nullable=True),
    sa.Column('role_clain_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('role_clain_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roleclaims')
    # ### end Alembic commands ###
