"""Bug fix in the models

Revision ID: 4f1c61f14975
Revises: 465a0df1bbcd
Create Date: 2025-03-15 21:11:00.927856

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f1c61f14975'
down_revision = '465a0df1bbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrole',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_role_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.drop_constraint('roleclaims_role_id_fkey', 'roleclaims', type_='foreignkey')
    op.create_foreign_key(None, 'roleclaims', 'roles', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roleclaims', type_='foreignkey')
    op.create_foreign_key('roleclaims_role_id_fkey', 'roleclaims', 'user', ['role_id'], ['id'])
    op.drop_table('userrole')
    # ### end Alembic commands ###
