"""removed backpropagtion property for  item sub categories  

Revision ID: 694599d565ae
Revises: e9c104737d70
Create Date: 2025-03-16 11:40:36.322151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '694599d565ae'
down_revision = 'e9c104737d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
