"""remove the semester relationshipt for course.

Revision ID: 7581986ba576
Revises: b0ef610f26c5
Create Date: 2025-07-04 11:20:24.034090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7581986ba576'
down_revision = 'b0ef610f26c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_semester_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'semester_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('semester_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('courses_semester_id_fkey', 'courses', 'semesters', ['semester_id'], ['semester_id'])
    # ### end Alembic commands ###
