"""removed backpropagation property for item category

Revision ID: 80ec995ad568
Revises: 95001e64e0d0
Create Date: 2025-03-15 14:34:16.073551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80ec995ad568'
down_revision = '95001e64e0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
