"""semester and user relationship updated

Revision ID: 8f769a87bbdc
Revises: 7581986ba576
Create Date: 2025-07-04 11:23:26.959626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8f769a87bbdc'
down_revision = '7581986ba576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
