"""Fixed relationship between itemcategroy and itemsubcategory

Revision ID: 8fd66ba936f3
Revises: 694599d565ae
Create Date: 2025-03-16 12:52:43.864139

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8fd66ba936f3'
down_revision = '694599d565ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
