"""Add Item Category table

Revision ID: 95001e64e0d0
Revises: 1a31ce608336
Create Date: 2025-03-15 12:08:32.985090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95001e64e0d0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemcategory',
    sa.Column('item_category_isactive', sa.Boolean(), nullable=False),
    sa.Column('item_category_id', sa.Uuid(), nullable=False),
    sa.Column('item_category_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_category_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('item_category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemcategory')
    # ### end Alembic commands ###
