"""added backpopulation th item subcategory

Revision ID: d8ffdcf0d165
Revises: 8fd66ba936f3
Create Date: 2025-03-22 08:55:02.699810

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8ffdcf0d165'
down_revision = '8fd66ba936f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
