"""added item sub categories table 

Revision ID: e9c104737d70
Revises: 4f1c61f14975
Create Date: 2025-03-16 11:39:01.696901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e9c104737d70'
down_revision = '4f1c61f14975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemsubcategory',
    sa.Column('item_subcategory_isactive', sa.Boolean(), nullable=False),
    sa.Column('item_category_id', sa.Uuid(), nullable=False),
    sa.Column('item_subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('item_subcategory_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_subcategory_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_category_id'], ['itemcategory.item_category_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('item_subcategory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemsubcategory')
    # ### end Alembic commands ###
