"""relationship are updated for ItemSubcatergory -> ItemCategory

Revision ID: ffce0c4d5832
Revises: d8ffdcf0d165
Create Date: 2025-03-22 14:05:57.513788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ffce0c4d5832'
down_revision = 'd8ffdcf0d165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
